# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charge.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "charge.ChargeRequest" do
    optional :url, :string, 1
  end
  add_message "charge.ChargeResponse" do
    optional :url, :string, 1
  end
end

module Charge
  ChargeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("charge.ChargeRequest").msgclass
  ChargeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("charge.ChargeResponse").msgclass
end
