# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: charge.proto for package 'charge'

require 'grpc'
require 'charge_pb'

module Charge
  module UrlChargeService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'charge.UrlChargeService'

      rpc :charge, ChargeRequest, ChargeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
